export const GET_MY_COMMENTS = 'negotation/get_my_comments'
export const GET_MY_COMMENTS_FAILED = 'negotation/GET_MY_COMMENTS_FAILED'
export const GET_MY_COMMENTS_SUCCESS = 'negotation/GET_MY_COMMENTS_SUCCESS'

export const GET_FACEBOOK_COMMENTS = 'negotation/GET_FACEBOOK_COMMENTS'
export const GET_FACEBOOK_COMMENTS_FAILED = 'negotation/GET_FACEBOOK_COMMENTS_FAILED'
export const GET_FACEBOOK_COMMENTS_SUCCESS = 'negotation/GET_FACEBOOK_COMMENTS_SUCCESS'

export const ON_ADD_NEGOTATION = 'ON_ADD_NEGOTATION'
export const ON_ADD_NEGOTATION_FAILED = 'ON_ADD_NEGOTATION_FAILED'
export const ON_ADD_NEGOTATION_SUCCESS = 'ON_ADD_NEGOTATION_SUCCESS'

export const ON_EDIT_NEGOTATION = 'ON_EDIT_NEGOTATION'
export const ON_EDIT_NEGOTATION_FAILED = 'ON_EDIT_NEGOTATION_FAILED'
export const ON_EDIT_NEGOTATION_SUCCESS = 'ON_EDIT_NEGOTATION_SUCCESS'

export const ON_SEND_INVOICE = 'ON_ADD_COMMENT'
export const ON_SEND_INVOICE_FAILED = 'ON_SEND_INVOICE_FAILED'
export const ON_SEND_INVOICE_SUCCESS = 'ON_SEND_INVOICE_SUCCESS'

export const ON_RENEW = 'ON_RENEW'
export const ON_RENEW_FAILED = 'ON_RENEW_FAILED'
export const ON_RENEW_SUCCESS = 'ON_RENEW_SUCCESS'

export const ON_CANCEL = 'ON_CANCEL'
export const ON_CANCEL_FAILED = 'ON_CANCEL_FAILED'
export const ON_CANCEL_SUCCESS = 'ON_CANCEL_SUCCESS'

export const ON_SET_SELECTED_NEGOTIATION = 'ON_SET_SELECTED_NEGOTIATION'


// export const GET_MY_PRODUCTS = 'negotation/get_my_products'
// export const GET_MY_PRODUCTS_FAILED = 'negotation/GET_MY_PRODUCTS_FAILED'
// export const GET_MY_PRODUCTS_SUCCESS = 'negotation/GET_MY_PRODUCTS_SUCCESS'

