export const GET_MY_COMMENTS = 'get_my_comments'
export const GET_MY_COMMENTS_FAILED = 'GET_MY_COMMENTS_FAILED'
export const GET_MY_COMMENTS_SUCCESS = 'GET_MY_COMMENTS_SUCCESS'

export const ON_ADD_COMMENT = 'ON_ADD_COMMENT'
export const ON_ADD_COMMENT_FAILED = 'ON_ADD_COMMENT_FAILED'
export const ON_ADD_COMMENT_SUCCESS = 'ON_ADD_COMMENT_SUCCESS'